### PR TITLE
[WIP] feat: adding migration guides

### PR DESCRIPTION
**Pull request by AoDev**
Note: this is work in progress, open to discussion, etc.

## What is this about: documenting possible migration guides
Guides about possible migrations in the mobx react ecosystem would be useful to save people's time. Sometimes it can be a full article, and sometimes it can be a simple link to another page of the docs as patterns evolve and will be documented in other sections.

This PR in particular wants to start with `mobx-react` vs `mobx-react-lite` and the new context API.

## What prompted the PR
mobx-react-lite readme mentions ["why no provider inject"](https://github.com/mobxjs/mobx-react-lite#why-no-providerinject). Having a more complete example would be helpful as more and more people will upgrade or write new apps with a major React version in the future but the legacy context API will be dropped. 

## Todos
- [ ] The equivalent / replacement of typical app bootstrapping with a root store in top level component.

### CODE REVIEW

**Comment by FredyC** [comment]
Thank you for contribution.

Thing is that we probably don't need a migration guide per se. The `mobx-react-lite` was mostly a temporary project to offer React Hooks support ASAP. The library is already incorporated in upcoming [`mobx-react@6`](https://github.com/mobxjs/mobx-react/issues/640). In the future, `mobx-react@7` will most likely drop class support and it will effectively become this library and this site will be its docs.

So as you see it's not really a goal to lead people to migrate now and then back again. It's meant for people who embraced hooks and want to try it out with MobX.

Have you read the page https://mobx-react.netlify.com/libraries along with https://mobx-react.netlify.com/state-how? These should give a pretty good picture of a "migration". I will be adding more recipes over time for sure, but nothing so explicit.

**Comment by FredyC** [comment]
Thanks for explaining your confusion. I see where are you coming from.

> "The contrived part" is that the code shown in these examples always shows everything declared in the same scope. Here is the example in our docs.

It's not exactly possible to write a real application as a part of docs. Even if it would, there is so many variations and approaches that can be used that showing a singular one wouldn't be that useful. Contrived examples give you an option to think about various concepts and pick the one that feels right.

> In some "new context api" examples, I did see people writing modules, as one would expect (different UI components, complex models/stores), and they actually have to import the "context" created in a different module.

That can be considered caveat of Context, but why would you actually import the context of another module? It feels like a halfway attempt for modular architecture. In case one module needs to even read the state of another one, then it's already breaking rule of modularization imo.

> using mobx-react "legacy", I didn't have to rely on my own modules to be able to provide and inject data.

Yes, that's because `mobx-react` exported a single Provider. You were kinda forced to put everything in there. In case you would use it multiple times, you would be overwriting the previous value. It works the same with Context except it's under your control and you can set up as many Providers as you need.

> I would just do import {inject} from 'mobx-react' and decorate my component. No explicit "import myCustomContext".

You don't really need to import the context object, import `useStore` as drafted in the example. It already carries the information about context so it's very similar to `inject`.

> I would have to export my rootStore and make my components import it directly?

You don't have to, but it would probably work as well. The caveat of global variables is problematic writing of tests.

**Comment by AoDev** [comment]
Thank you for your reply. 

I am not sure to understand this:

> That can be considered caveat of Context, but why would you actually import the context of another module? It feels like a halfway attempt for modular architecture. In case one module needs to even read the state of another one, then it's already breaking rule of modularization imo.

I write my apps partly based on having a "root store" that can be injected with provider/inject, and concepts written in this article: [how-to-decouple-state-and-ui-a-k-a-you-dont-need-componentwillmount](https://hackernoon.com/how-to-decouple-state-and-ui-a-k-a-you-dont-need-componentwillmount-cc90b787aa37)

In the past 3 years, I haven't needed lifecycle methods or hooks, and didn't need to import any state / context from somewhere. The only "exception" is that mobx-react provide/inject would do the job if I needed to inject directly the root store in some component.

**Comment by FredyC** [comment]
> I write my apps partly based on having a "root store" that can be injected with provider/inject,

Yes, that's completely fine. Just define a single Context, have the "root store" in it and export `useRootStore` which will serve as a replacement for `inject`.

Great thing is that you no longer need to worry about strings everywhere, eg. `inject("rootStore")` because the `useRootStore` already carries that information. If your store grows bigger, you might even consider making more granular hooks, eg. `useOrderStore` that abstracts away where in the store is the information about the order.

**Comment by AoDev** [comment]
I guess my only problem / question, was then that I was not expecting having to import that `"useRootStore"` somewhere. It gives more control, but now I need to get a reference to it, everywhere I want to use it.
Unless I setup some alias / module resolver in the build, I will have the code full of 
```
import {useRootStore from} '../../rootStoreContext'
import {useRootStore from} '../../../rootStoreContext'
import {useRootStore from} '../../../../rootStoreContext'
```
And these will just break every time I move files around. (except if I have an alias in the build)
Or did I miss something?

**Comment by FredyC** [comment]
You are correct, I guess that's the tradeoff. Your IDE should be able to offer refactoring capabilities so when you move files around it fixes paths for you. I know that VSCode can handle it for TypeScript code very well. Not sure about JavaScript only.

**Comment by AoDev** [comment]
> You are correct, I guess that's the tradeoff. 
Ok :) 

Thank you for your time answering my questions. Do you see anything discussed here that could be part of the docs in one form or another? (pretty sure not only I will wonder about this)

**Comment by FredyC** [comment]
I made a new addition to docs a few minutes ago. Probably nothing surprising for you now, but you have kinda inspired me with your questions. Hopefully, it will help others.

https://mobx-react.netlify.com/recipes-inject

**Comment by AoDev** [comment]
> (kids, don't do drugs) 

lol :D

Nice additions, thanks a lot.

Then from our discussion / additions, I have a new question: what's the point of using context with observables now that I import my store "directly"?

Why not just:
```js
// MyStore.js
class MyStore {
  @observable value = 'value'
  @action.bound updateValue (...)
}

export const myStore = new MyStore()
```

Some observer component
```js
import {myStore} from '...'

function MyComponent {
  return <div>{myStore.value}</div>
}

export default observer(MyComponent)
```

Why do I need context then? I thought context was a dependency injection mechanism. But if we need to use JS module imports, it's the same than having a singleton that we just have to import. And observer reacts automatically, so no need for props or anything. A "connected component" just need to import the store instance directly. 

No?

**Comment by FredyC** [comment]
https://github.com/mobxjs/mobx-react-lite/issues/17

In short, if you don't write tests, then don't worry and go global :)

Either way good point, I will mention it in docs as well.

**Comment by AoDev** [comment]
Not sure about the "test" problem.

At what level is it a problem? in unit tests?
You can split the "provider" as some tiny wrapper component that will provide the store to the actual view component.
So we can import the "view" and provide it anything during the tests.

**Comment by FredyC** [comment]
Depends on what kind of unit tests it is. Testing UI components it doesn't matter. But anything more serious means that tests will be sharing the same state and if you don't reset it properly, it will cause flakiness - adding/removing one test might break other tests.

**Comment by 100ideas** [comment]
> I guess my only problem / question, was then that I was not expecting having to import that `"useRootStore"` somewhere. It gives more control, but now I need to get a reference to it, everywhere I want to use it.
> Unless I setup some alias / module resolver in the build, I will have the code full of
> 
> ```js
> import {useRootStore} from '../../rootStoreContext'
> import {useRootStore} from '../../../rootStoreContext'
> import {useRootStore} from '../../../../rootStoreContext'
> ```

@AoDev, check out how this codebase uses webpack to enable root path imports like so:

see how the AuthStore is imported https://github.com/outline/outline/blob/master/app/components/Sidebar/Settings.js#L24
```js
import SidebarLink from './components/SidebarLink';
import HeaderBlock from './components/HeaderBlock';
import AuthStore from 'stores/AuthStore';
```

I think this is enabled in webpack.config.js https://github.com/outline/outline/blob/master/webpack.config.js#L39
```js
module.exports = {
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/static/',
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: [
          path.join(__dirname, 'node_modules')
        ],
        include: [
          path.join(__dirname, 'app'),
          path.join(__dirname, 'shared'),
        ],
        options: {
          cacheDirectory: true
        }
},
```

**Comment by AoDev** [comment]
@100ideas thank you for the response. I don't have any problem setting up module resolution with webpack or Babel. That is not the problem I was arguing about though. Using aliases is a build problem, not the same than resolving a run time dependency injection problem. They are different problems.

**Comment by FredyC** [comment]
I don't really see an issue with long relative paths. With a proper refactoring-able IDE it doesn't really matter, it will take care of it for you. Aliases look great, I've been using them heavily for a while, but they generally cause many issues across various tooling (eg. Storybook, Jest, Cypress...) so I am avoiding that now.

**Pull request closed without merging**
